# Generated by Django 4.2.23 on 2025-10-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docprocessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeProcessedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('summarize', 'Summarize'), ('generate', 'Generate Answers'), ('analyze', 'Analyze')], max_length=20)),
                ('result_text', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_results', to='docprocessor.youtubevideo')),
            ],
        ),
    ]
