# Generated by Django 4.2.23 on 2025-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessor', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('hf', 'Hugging Face')], default='openai', max_length=20)),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Setting',
                'verbose_name_plural': 'AI Provider Settings',
            },
        ),
    ]
