# Generated by Django 4.2.23 on 2025-10-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessor', '0004_aiprovidersetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIProviderSetting',
        ),
    ]
