# Generated by Django 4.2.23 on 2025-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docprocessor', '0005_delete_aiprovidersetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
